apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
  labels:
    type: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-pv-2"